### ISSUE TITLE
Take into account arenas and battlegrounds ?

### ISSUE THREAD

**Issue by abervoet** [rsuurd/killpoints#10]
Hi,

Is it intended that there is no killpoints for bg and arenas ?

**Comment by rsuurd** [comment]
I don't know which api endpoint has those numbers

**Comment by abervoet** [comment]
Looks like the statistics api has this data ( category "id": 21, "name": "Player vs. Player"), but only as totals, which would be inaccurate for characters that have won bgs/arenas before legion.

**Comment by rsuurd** [comment]
There is a /pvp endpoint as well but that's weekly

**Comment by rsuurd** [comment]
Closing this, i will add this if the API will expose this kind of stuff.
