### ISSUE TITLE
Special Char Issue

### ISSUE THREAD

**Issue by Swiftdeus** [rsuurd/killpoints#11]
Some servers, such as Emerald Dream, have a space in the name. The URL adds a "+", but it does not link to the proper page. "-" and "_" also do not work.

-Swiftdeus

**Comment by rsuurd** [comment]
Do you have some characters on those servers i can test with in order to get this fixed?

Myself i am on Twisting Nether and that server works just fine, so i'm curious what the problem exactly is.

**Comment by Swiftdeus** [comment]
yeah, my character name is "Swiftdeus" on Emerald Dream and my girlfriends name is "Kitsyn". You could try a name too with special characters "Goodíe".

**Comment by rsuurd** [comment]
What browser are you using? It works just fine on Chrome

**Comment by Swiftdeus** [comment]
I am using chrome...

**Comment by Swiftdeus** [comment]
![image](https://cloud.githubusercontent.com/assets/4662165/22941661/9fee58ae-f2a3-11e6-931d-b5b7dbd453cc.png)

**Comment by rsuurd** [comment]
I am not sure what is going wrong for you - do you have any blocking extensions installed? PrivacyBadger, Ghostery, etc?

![kps](https://cloud.githubusercontent.com/assets/361016/22942840/7015dc54-f2eb-11e6-9d91-41f9f2d7a640.png)

**Comment by Swiftdeus** [comment]
No, Nothing other than Adblock, but I see you have that too. The URLs appear to be the same as well.
