### ISSUE TITLE
support fetch for IE and Safari

### ISSUE THREAD

**Issue by Undertoe** [rsuurd/killpoints#2]
Region: US
Realm: Baelgun
Charactor name: Terrynlock.

**Comment by rsuurd** [comment]
What browser do you use? Chrome and Firefox should work.

**Comment by Undertoe** [comment]
Chrome.


________________________________

**Comment by Undertoe** [comment]
Could it be a firewall issue?

**Comment by rsuurd** [comment]
Yes, or certain extensions that block javascript calls (PrivacyBadger for example)

**Comment by Undertoe** [comment]
All right thats more than likely the issue. 

A side note: I tried it on mobile and it just spun for about 3 minutes before I gave up.

**Comment by rsuurd** [comment]
should be done now
