### ISSUE TITLE
China Realms Supporting?

### ISSUE THREAD

**Issue by euloanty** [rsuurd/killpoints#5]
Please. I beg you

**Comment by rsuurd** [comment]
I tried finding all chinese realmnames but i can't read chinese. Can you provide a list of realmnames?  Then i can add them.

**Comment by euloanty** [comment]
[realms.txt](https://github.com/rsuurd/killpoints/files/756363/realms.txt)
a lua table

**Comment by MrGba2z** [comment]
I tried to look into it but I doubt the CN APIs are still broken

**Comment by rsuurd** [comment]
Yes, i've tried a few api calls but it seems the API for china is not usable.
