### ISSUE TITLE
Percentage bar

### ISSUE THREAD

**Issue by forhorglingrads** [rsuurd/killpoints#6]
Progress bad is calculating overall percentage rather than the percentage of the amount you need from 1 to the next.

For example: I have 4 legendaries, and and i have 2940 kill points right now. 2940 is 61% of 4800 (the 5th legendary) which is what your calculator is doing.

What it needs to be doing is calculating the amount you need from one to the next. So from 4 to 5 I would need 2619 points. I have 759 out of 2619 which is 28.9%.

**Comment by rsuurd** [comment]
I'll take a look. The progressbar was added as a joke though, since the dropchance is random anyway. That's why there's a Sephuz at the end as well :)

**Comment by rsuurd** [comment]
Progress bar removed due to significant changes in legendary drops / crafts.
