### ISSUE TITLE
New statistics update from February 6 

### ISSUE THREAD

**Issue by aTei** [rsuurd/killpoints#7]
http://www.mmo-champion.com/threads/2091126-Real-Legendary-drop-rates-and-other-statistics-for-9785-chars-Spreadsheet

**Comment by rsuurd** [comment]
Yes, i've seen it - i'll get around to do that this weekend

**Comment by rsuurd** [comment]
I've added the extra dungeon calculations. I'm not sure how to track BG's / RBG's and arenas. There is a /pvp api but i don't think that's usable.
